### ISSUE TITLE
word_count tests fail to build with gcc 8.1.1

### ISSUE THREAD

**Issue by mikewalker** [exercism/c#310]
When compiling the tests for word_count exercise I get the following error. This may be something to do changes in recent versions of gcc. I have eliminated errors generated by my code, but without modifying the test I cannot get past this one.

Development Environment
- Fedora 28
- GCC 8.1.1

Error generated running 'make test'

Compiling tests.out
test/test_word_count.c: In function ‘test_max_length_word’:
test/test_word_count.c:361:4: error: ‘strncpy’ output truncated before terminating nul copying 50 bytes from a string of the same length [-Werror=stringop-truncation]
    strncpy(expected_solution[index++].text,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            "thisisaveeeeeerylongwordtypedwithoutusinganyspaces",
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            MAX_WORD_LENGTH);
            ~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

**Comment by mikewalker** [comment]
In order to proceed with this exercise I have found a possible solution by updating the test a bit. Turning off the warning allows me to continue with the exercise in the recommended TDD fashion. I'm not sure that this is the right solution but it works for me at the moment.

   #pragma GCC diagnostic ignored "-Wstringop-truncation"
   strncpy(expected_solution[index++].text,
           "thisisaveeeeeerylongwordtypedwithoutusinganyspaces",
           MAX_WORD_LENGTH);
   #pragma GCC diagnostic pop
